import Head from "next/head";
import axios from "axios";
import { server } from "@/confing";
import TopRatedMovies from "@/components/TopRatedMovies";

export default function Homepage({ movies }) {
  console.log(movies);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopRatedMovies movies={movies.results}/>
    </>
  );
}

export async function getStaticProps() {
  const res = await axios(`${server}/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`);
  const movies = res.data;

  return {
    props: { movies }
  }
}
// https://api.themoviedb.org/3/movie/top_rated?api_key=<<api_key>>&language=en-US&page=1
